### ISSUE TITLE
Interoperability: How to make the Format compatible to RNCryptor-ObjC?

### ISSUE THREAD

**Issue by itinance** [RNCryptor/ruby_rncryptor#5]
I've tried to encrypt both a plain string and also a binary file (image) with this ruby-lib and to decrypt with RNCryptor-ObjC. Apparently the formats aren't compatible to each other. Or did i somethong wrong?

Ruby-Code:

```
require './lib/ruby_rncryptor'
require "base64"

password = "n3v3r gue55!!"

encrypted = RubyRNCryptor.encrypt("This is a tiny bit of text to encrypt", password)
puts Base64.encode64(encrypted)

```

I tried also without encode64:

```
require './lib/ruby_rncryptor'

password = "n3v3r gue55!!"

encrypted = RubyRNCryptor.encrypt("This is a tiny bit of text to encrypt", password)
puts encrypted

```

I then called it with "ruby enc.rb > data.enc", to put the output into a file called **data.enc**. 
The file called **data.enc** i've bundled with my iOS-App and tried to decrypt it with the RNCryptor-Objc-Library:

```
  NSString *password = @"n3v3r gue55!!";
  
    // Get the main bundle for the app.
  NSBundle* mainBundle = [NSBundle mainBundle];
  
  NSString* bundlePath = [[NSBundle mainBundle] bundlePath];
  NSLog(@"Bundle Path: %@", bundlePath);
  
  NSString* sourceFile = [bundlePath stringByAppendingFormat:@"/content/data.enc"];
  NSLog(@"Found source file: %@", sourceFile);

  NSData *data = [[NSFileManager defaultManager] contentsAtPath:sourceFile];

  NSError *error;
  
  NSData *decryptedData = [RNDecryptor decryptData:data
                                      withPassword:password
                                             error:&error];
  
  NSLog(@"%@", decryptedData);

```

The content of decryptedData is just plain **nil** and the error says "Unknown header". I can assure, that the bundling of the file into the app wasn't a problem. We bundle lots of files and read them out that way. Doing NSLog here would output the content of the file.
I've tried both with and without base64Encoder. On the ruby-lib, it doesnt matter because decrypt() can somewho handle both.

The motivation behind is that we are looking to handle encrypted and decrpyted Data both on a device and also outside on a backend-server. Therefor we need the interoperability between multiple platforms. So we are looking for a library, that can fit our needs.

Did i something wrong or is it still not possible what i want to achieve with RNCryptor/xxx?

**Comment by rnapier** [comment]
I haven't looked at the ruby port in a long time (and I won't have a computer until tomorrow), but I would strongly suspect you're not writing the exact binary data from ruby. I suspect they its getting encoded some way (you should not base64 encode it unless you plan to decode it before handing to the decryptor). The first byte of the data should be 03. That error indicates that it isn't.

**Comment by timestretch** [comment]
It worked for me with some changes. I wrote to a file with Ruby instead of just sending stdout to a file.

`require 'ruby_rncryptor'

password = "n3v3r gue55!!"
encrypted = RubyRNCryptor.encrypt("This is a tiny bit of text to encrypt", password)
File.open("data.enc", "w+") do |fp|
	fp.write(encrypted)
end
`

Here I had to adjust the code to get the file path from bundle. I also added some assertions.

`	NSString *password = @"n3v3r gue55!!";
	
	// Get the main bundle for the app.
	NSString *filePath = [[NSBundle mainBundle] pathForResource:@"data" ofType:@"enc"];
	NSData *data = [NSData dataWithContentsOfFile:filePath];
	NSAssert(data, @"Data is nil");
	
	NSError *error = nil;
	NSData *decryptedData = [RNDecryptor decryptData:data
										withPassword:password
											   error:&error];
	if (error != nil)
		NSLog(@"error = %@", [error localizedDescription]);
	
	NSAssert(decryptedData, @"Decrypted data is nil");
	NSString *string = [NSString stringWithUTF8String:[decryptedData bytes]];
	NSAssert(decryptedData, @"Decrypted data is nil");
	NSLog(@"%@", string);
`
